services:
  grafana:
    build:
      context: ./.config
      args:
        grafana_image: grafana-enterprise
        grafana_version: 11.3.0
        development: ${DEVELOPMENT:-false}
    container_name: 'grafana-sankey-panel'
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-sankey-panel
      - ./provisioning:/etc/grafana/provisioning
    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-sankey-panel:debug
      GF_LOG_LEVEL: debug
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-sankey-panel
